version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: 'circleci/node:latest'
on-main: &on-main
  filters:
    branches:
      only:
        - main
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM dependencies
          keys:
            - npm-{{ checksum "package.json" }}
            - npm-
      - run:
          name: Install NPM dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test
      - save_cache:
          name: Save NPM dependencies
          paths:
            - ./node_modules/
          key: npm-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy-staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy on staging
          command: echo "Deploying on staging....... Done"
      - persist_to_workspace:
          root: ~/repo
          paths: .
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Release a new verision
          command: npx semantic-release
workflows:
  version: 2
  release:
    jobs:
      - test
      - deploy-staging:
          <<: *on-main
          requires:
            - test
      - manual-test:
          type: approval
          <<: *on-main
          requires:
            - test
            - deploy-staging
      - release:
          <<: *on-main
          requires:
            - manual-test
